FROM bioconductor/bioconductor_docker:devel

RUN apt update
RUN apt install -y vim

USER rstudio

WORKDIR /home/rstudio

RUN git clone --branch vjc_idx_fix_gpu https://github.com/vjcitn/PyTorch-BigGraph

WORKDIR PyTorch-BigGraph


RUN pip install torch
RUN PBG_INSTALL_CPP=1 pip install .
RUN Rscript -e "BiocManager::install('devtools')"
RUN Rscript -e "BiocManager::install('vjcitn/BiocPBG', dependencies=TRUE)"

# to use in jetstream with GPU 
# docker run -v /home/exouser/KEEP:/tmp/KEEP --gpus all --ipc=host -ti vjcitn/pbg_gpu:0.0.0 bash

